<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Void2610.Arinn.Tests</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);UNITY_INCLUDE_TESTS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(RepoRoot)Tests/Editor/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Void2610.Arinn/Void2610.Arinn.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.14.0" />
  </ItemGroup>
</Project>
