<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Void2610.Arinn.InputSystem</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);ARINN_INPUT_SYSTEM</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="$(RepoRoot)InputSystem/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Void2610.Arinn/Void2610.Arinn.csproj" />
  </ItemGroup>
</Project>
